#NAME: Bianheng Cao
#EMAIL: bianhengcao@gmail.com

default: 
	@gcc -w -g -Wall -Wextra lab1a.c -o lab1a
clean:
	@rm -f lab1a
	@rm -f lab1a.tar.gz
dist:
	@tar -czf lab1a.tar.gz lab1a.c Makefile README
