#NAME:Bianheng Cao
#EMAIL:bianhengcao@gmail.com

default:
	@gcc -w -g -Wall -Wextra -o lab3a lab3a.c
clean:
	@rm -f lab3a lab3a.tar.gz
dist:
	@tar -czf lab3a.tar.gz lab3a.c Makefile README ext2_fs.h 
